### ISSUE TITLE
Does not work with latest cpfw appliance

### ISSUE THREAD

**Issue by Savemech** [thewisenerd/check.point.automaton#1]
Hi there, i'm trying to adopt this fancy, but no luck :no_good_man: 
regno, password and portal url's was replaced to proper one, then
python3 login.py

```
python3 login.py 
Traceback (most recent call last):
  File "login.py", line 193, in <module>
    main()
  File "login.py", line 176, in main
    rsa = getRSASettings(nacsid);
  File "login.py", line 93, in getRSASettings
    j = json.loads(r.text);
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

pip3 list

```
Brlapi (0.6.1)
chardet (2.2.1)
colorama (0.2.5)
command-not-found (0.3)
defer (1.0.6)
html5lib (0.999)
httplib2 (0.8)
language-selector (0.1)
louis (2.5.3)
oauthlib (0.6.1)
oneconf (0.3.7.14.04.1)
pip (1.5.4)
piston-mini-client (0.7.5)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycurl (7.19.3)
pygobject (3.12.0)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
pyxdg (0.25)
requests (2.11.1)
rsa (3.4.2)
setuptools (3.3)
simplejson (3.8.2)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
ubuntu-drivers-common (0.0.0)
ufw (0.34-rc-0ubuntu2)
unattended-upgrades (0.1)
urllib3 (1.7.1)
usb-creator (0.2.23)
wheel (0.24.0)
xkit (0.0.0)
```

**Comment by thewisenerd** [comment]
hello, this works with a login portal at my university that looks something like this: 

![...](http://i.imgur.com/N978Okr.png)

If you have something similar, you might need to figure out how it's implemented.

**Comment by Savemech** [comment]
i have exactly same, how i could troubleshoot this to help you find out which part of code working improperly?

**Comment by thewisenerd** [comment]
try getting a HAR (HTTP Archive) from Chrome Debugger Tools with your normal login URL. Maybe I can point you in the direction.
